# Generated by Django 2.2.3 on 2019-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_quotation',
            name='contract_exclude_tax',
            field=models.IntegerField(blank=True, db_column='contract_exclude_tax', null=True, verbose_name='契約額合計(税抜)'),
        ),
    ]
